# This workflow will run the project's scripts to ensure successful install

name: build

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches: [ master ]

jobs:
    build:

        strategy:
            matrix:
                os: [ "ubuntu-18.04" ]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v1
        - name: Install apt packages
          run: make apt
        - name: Generate dotfile symlinks
          run: make dots
        - name: Install Docker-CE
          run: make docker
        - name: Install pip --user packages
          run: make pip
        - name: Install Visual Studio Code
          run: make vscode
        - name: Install abcde package
          run: make abcde
