# This workflow will run the project's scripts to ensure successful install

name: build

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches: [ master ]

jobs:
    build:

        strategy:
            matrix:
                os: [ "ubuntu-18.04" ]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v1
        - name: Install apt packages
          run: make apt
        - name: install miniconda and py37 env
          run: make conda
        - name: Install Docker-CE
          run: make docker
        - name: Install pip --user packages
          run: make pip
        - name: Configure and enable systemd user services
          run: make services
        - name: Install abcde package
          run: make abcde
        - name: Install Dropbox daemon and CLI
          run: make dropbox
        - name: Install latest Zoom .deb package
          run: make zoom
        - name: Install executable scripts to /usr/local/bin
          run: make bin
        - name: Install optional packages from source
          run: make -i source
        - name: Install Visual Studio Code
          run: make vscode
        - name: Generate dotfile symlinks
          run: make dots
